# Generated by Django 4.2.15 on 2024-11-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_orderitem_created_at_orderitem_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
    ]
